KusionStack/kusionstack.io

.github/workflows/deploy.yml
- deploy action only trigger on deploy branch
=> add deploy branch

docs/governance/contribute/contribute-docs.md, docusaurus.config.js, package-lock.json, package.json, yarn.lock
- Bump trim from 0.0.1 to 0.0.3
- remove mdx-mermaid plugin
=> Fix security warning

.github/workflows/cla.yml, .github/workflows/deploy.yml
- use CLA action
- use bot token for deploy action
```release-note
None
```
=> use CLA action

docs/user_docs/guides/argocd/drift-check-with-argocd.md
Issue Number: close #22 
Problem Summary:
=> optimize drift check with argocd, replace patch body with github file

docusaurus.config.js, package-lock.json, package.json, yarn.lock
Using the algolia crawler to get the website document information and store it in the `index` of the
app. And implement docsearch through intergrating  algolia search engine.
fix #30
docusaurus.config.js
test `index`(similar to a database) on the algolia's website and test search function in kusionstack.io with
```
$ npm install
$ npm run start
```
Open http://localhost:3000 in browser.
```release-note
None
```
=> chore(docusaurus.config.js): docsearch in kusionstack.io website

.github/workflows/cla.yml, .github/workflows/deploy.yml, docs/governance/contribute/_category_.json, docs/governance/contribute/git-guideline.md, docs/user_docs/guides/argocd/drift-check-with-argocd.md, docusaurus.config.js, package-lock.json, package.json, yarn.lock
/Users/shijun/Workspace/kusionstack.io/docs/governance/contribute/git-guideline.md
add git-guideline.md to show more details about naming branch, commit message and CLA.
```release-note
None
```
=> docs(kusionstack.io/docs): add git guideline

.github/workflows/cla.yml
.github/workflows/cla.yml
```release-note
None
```
=> Add kusionstack-bot and dependabot[bot] to CLA workflow allowlist

package-lock.json, package.json, yarn.lock
https://github.com/KusionStack/kusionstack.io/security
```release-note
None
```
=> fix: security warning

docs/governance/intro/roadmap.mdx
=> Update engine roadmap

static/install.sh
=> chore: add install.sh for kusionup

docs/reference/lang/lang/spec/modules.md, docs/reference/lang/model/datetime.md
=> chore: bump time system module to datetime.

i18n/en/code.json, src/components/HomepageFeatures.js
Refine kcl introduction on home page including Chinese and English version.
```release-note
None
```
=> chore: refine kcl introduction at home page.

i18n/en/docusaurus-plugin-content-docs/current.json, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/lang/tour.md
=> fix: npm deploy action

.github/workflows/build.yml, docs/user_docs/getting-started/kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kcl.md
re #82. Translate KCL quick start document.
```release-note
None
```
=> feat: add kcl quick start english version.

docs/reference/lang/lang/spec/kcl-spec.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/lang/spec/kcl-spec.md
* Translate the titles of some of the KCL spec's documentation into English
* Reorganized parts of the KCL spec documentation
```release-note
None
```
=> feat: translate kcl spec headers to English

docs/user_docs/concepts/kcl-lang.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/concepts/kcl-lang.md
Refine kcl concept documents with Chinese and English version.
```release-note
None
```
=> feat: refine kcl concept documents with Chinese and English version.

.github/workflows/deploy.yml
=> fix: deploy action

i18n/en/docusaurus-plugin-content-docs/current.json, i18n/zh-CN/docusaurus-plugin-content-docs/current.json
=> chore: remove unknown translate keys

blog/2022-09-16-lean-from-scale-practice/index.md
Update blog: fix images of blog:  What We Learned From Large-scale Platform Engineering Practices
```release-note
None
```
=> Update blog: fix images

docs/reference/lang/plugin/overview.md
feat: add kcl plugin English document.
```release-note
None
```
=> feat: add kcl plugin English document.

docs/reference/lang/model/_category_.json, docs/reference/lang/model/base64.md, docs/reference/lang/model/builtin.md, docs/reference/lang/model/crypto.md, docs/reference/lang/model/datetime.md, docs/reference/lang/model/index.md, docs/reference/lang/model/json.md, docs/reference/lang/model/math.md, docs/reference/lang/model/net.md, docs/reference/lang/model/overview.md, docs/reference/lang/model/regex.md, docs/reference/lang/model/units.md, docs/reference/lang/model/yaml.md
feat: add kcl system module English documents.
```release-note
None
```
=> feat: add kcl system module English documents.

i18n/en/docusaurus-plugin-content-docs/current.json, i18n/en/docusaurus-theme-classic/navbar.json, i18n/zh-CN/docusaurus-theme-classic/footer.json, i18n/zh-CN/docusaurus-theme-classic/navbar.json
=> i18n: translate menu name

docs/reference/lang/plugin/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/lang/plugin/overview.md
=> feat: refine kcl plugin English document.

i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/cli/kcl/docgen.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/cli/openapi/_category_.json, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/cli/openapi/spec.md
ref/cli/kcl/docgen
```release-note
None
```
=> en: docgen

docs/user_docs/support/faq-kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
feat: add kcl faq English documents.
```release-note
None
```
=> feat: add kcl faq English documents.

docs/user_docs/support/install-error.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/install-error.md
feat: add faq install document English version.
feat: add faq install document English version.
```release-note
None
```
=> feat: add faq install document English version.

docs/user_docs/guides/argocd/drift-detection-by-argocd.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/argocd/drift-detection-by-argocd.md
add prerequisites
```release-note
add prerequisites: install argocd first
```
=> polish drift-detection-by-argocd

docs/user_docs/guides/adopting/_category_.json, docs/user_docs/guides/adopting/from_kubernetes.md, docs/user_docs/guides/adopting/index.md, i18n/zh-CN/docusaurus-plugin-content-docs/current.json
=> en: translate user-docs/guides/adopting

docs/reference/cli/kcl/docgen.md, docs/reference/cli/kcl/fmt.md, docs/reference/cli/kcl/lint.md, docs/reference/cli/kcl/overview.md, docs/reference/cli/kcl/test.md, docs/reference/cli/kcl/vet.md
ref/cli/kcl/*
polish translate
```release-note
None
```
=> polish cli kcl

blog/2022-06-07-sense-of-open-day/index.md, blog/2022-09-15-declarative-config-overview/index.md
=> chore: add blog English sidebar title.

docs/user_docs/support/faq-cli.md
docs/user_docs/support/faq-cli.md
translate faq-cli
```release-note
None
```
=> en: faq_cli

blog/2022-09-15-declarative-config-overview/index.md
refactor: refine performance env, cli and version in `The Landscape of Declarative Configuration` blog.
```release-note
None
```
=> refactor: refine performance env, cli and version.

docs/user_docs/guides/organizing-projects-stacks/mapping.md
```release-note
en: organize projects and stacks
```
=> en: organize projects and stacks

docs/user_docs/guides/working-with-k8s/1-deploy-server.md, docs/user_docs/guides/working-with-k8s/2-container.md, docs/user_docs/guides/working-with-k8s/3-monitoring.md, docs/user_docs/guides/working-with-k8s/4-service.md, docs/user_docs/guides/working-with-k8s/5-image-upgrade.md, docs/user_docs/guides/working-with-k8s/6-resource-spec.md, docs/user_docs/guides/working-with-k8s/7-differentiated-configuration.md
```release-note
en: deploy an app
en: configure main container
en: enable monitoring
en: expose service
en: upgrade image
en: configure resource spec
en: differentiated configurations
```
=> en: kusion/konfig with k8s

docs/reference/cli/openapi/crd-to-kcl.md, docs/reference/cli/openapi/openapi-to-kcl.md, docs/reference/cli/openapi/quick-start.md, docs/user_docs/guides/adopting/from_kubernetes.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/adopting/from_kubernetes.md
=> Update crd-to-kcl.md, fix the cmd name

docs/user_docs/getting-started/install/kusionup.md
re #160 
docs/user_docs/getting-started/install/kusionup.md
polish the install doc of kusionup, using consistent terminologies. fixed some typos and polish some ambiguous statements.
```release-note
None
```
=> polish kusionup install doc

src/pages/index.js
fix typo and grammar in homepage
fix #181
=> fix typo and grammar in homepage

docs/user_docs/support/faq-kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
re: #122. Add calculation between numeric unit values and numbers.
* docs/user_docs/support/faq-kcl.md
* i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
```release-note
None
```
=> feat(faq): add calculation between numeric unit values and numbers.

static/kclvm-artifact-go/index.html
feat: add kclvm-go-artifact domain go import.
```release-note
None
```
=> feat: add kclvm-go-artifact domain go import

docs/user_docs/getting-started/kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kcl.md
feat: add the kcl website link in the quick start document.
```release-note
None
```
=> feat: add the kcl website link in the quick start document.

static/scripts/install-kusion.ps1, static/scripts/install-kusion.sh, static/scripts/install.ps1, static/scripts/install.sh
=> feat: add install scripts

.github/workflows/install.yml
=> new CI workflow: check installation scripts

.github/workflows/install.yml, static/scripts/install-kusion.sh, static/stack/ci-test/std.golden.yaml, static/stack/kcl.yaml, static/stack/main.k, static/stack/project.yaml, static/stack/stack.yaml
=> new CI workflow: check brew install and scoop install

i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/usecases/deliver-hybrid-resources-project.md
fix the sidebar_position setting in deliver-hybrid-resources-project.md zh-CN doc
```release-note
None
```
=> fix the sidebar_position setting

static/helm-kcl/index.html, static/kpt-kcl-sdk/index.html
feat: add kpt-kcl-sdk and helm-kcl go imports.
```release-note
None
```
=> feat: add kpt-kcl-sdk and helm-kcl go imports.

static/kustomize-kcl/index.html
=> feat: add kustomize-kcl go imports.

static/kpm/index.html
=> feat: add kpm go imports.

.github/workflows/build.yml, .github/workflows/deploy.yml
Update the ubuntu version because of GitHub breaking changes
https://github.com/actions/runner-images/issues/6002
=> update ubuntu versions because of GitHub breaking changes

docs/user_docs/intro/kusion-intro.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/intro/kusion-intro.md
docs: polish KusionStack introduction English and zh-CN documents.
+ Minor the introduction English document because of some typos.
+ Translate and polish introduction zh-CN documents based on the introduction English document.
+ docs/user_docs/intro/kusion-intro.md
+ i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/intro/kusion-intro.md
```release-note
None
```
=> docs: polish kusion intro English and zh-CN documents.

docusaurus.config.js
chore: add more footers
```release-note
None
```
=> chore: add more footers

src/css/custom.css
UI: change the color theme of the announcement bar
in light mode:
in dark mode:
```release-note
None
```
=> UI: change the color theme of the announcement bar

docusaurus.config.js, i18n/en/code.json, src/pages/index.js
=> refactor homepage

src/pages/index.js
chore: update logos for the security feature.
```release-note
None
```
=> chore: update logos for the security feature.

docs/user_docs/getting-started/kcl.md, docs/user_docs/support/faq-cli.md, docs/user_docs/support/faq-kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kcl.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-cli.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/support/faq-kcl.md
docs: sync kcl-related documents from kcl-lang.io
```release-note
None
```
=> docs: sync kcl-related documents from kcl-lang.io

docs/user_docs/getting-started/usecases/deliver-the-wordpress-application-on-kubernetes-and-clouds.md
docs/user_docs/getting-started/usecases/deliver-the-wordpress-application-on-kubernetes-and-clouds.md
```release-note
None
```
=> fix some grammar issue for WordPress application demo

docusaurus.config.js
=> update github ref link

README.md, docs/user_docs/getting-started/kusion-ide.mdx, docs/user_docs/getting-started/usecases/deliver-first-project.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kusion-ide.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/usecases/deliver-first-project.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/intro/kusion-intro.md
- README.md
- docs/user_docs/getting-started/usecases/deliver-first-project.md
- docs/user_docs/getting-started/kusion-ide.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/intro/kusion-intro.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/kusion-ide.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/usecases/deliver-first-project.md
```release-note
None
```
=> docs(kusion-ide): translate user_docs en->zh and fix bugs in docs

i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/getting-started/install.md
```release-note
None
```
=> fix zh doc of cmd "scoop bucket add"

static/kube-api/index.html
=> feat(static): add kube-api page for go get

docs/user_docs/intro/kusion-intro.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/intro/kusion-intro.md
=> feat: refresh intro doc

docs/reference/model/naming-conventions.md, docs/reference/model/project-stack-config-items.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/naming-conventions.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model/project-stack-config-items.md
fix #292 
docs/reference/model & i18n/zh-CN/docusaurus-plugin-content-docs/current/reference/model
This PR updates kusion model library. 
```release-note
None
```
=> feat: update kusion model library

docs/user_docs/guides/iaas/_category_.json, docs/user_docs/guides/iaas/database.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/iaas/_category_.json, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/iaas/database.md
fix https://github.com/KusionStack/kusion/issues/525
docs/user_docs/guides/iaas/database.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user_docs/guides/iaas/database.md
This PR adds guides for IaaS resource of database accessory. 
```release-note
None
```
=> feat: add guides for database accessory

docusaurus.config.js
Click on the `blog` to jump to the link： https://medium.com/@kusionstack
```release-note
None
```
=> refactor: adjust blog link

docs/user_docs/concepts/index.md, docs/user_docs/config-walkthrough/_category_.json, docs/user_docs/config-walkthrough/_tagging.md, docs/user_docs/config-walkthrough/base_override.md, docs/user_docs/config-walkthrough/database.md, docs/user_docs/config-walkthrough/kcl_basics.md, docs/user_docs/config-walkthrough/monitoring.md, docs/user_docs/config-walkthrough/networking.md, docs/user_docs/config-walkthrough/operational_rules.md, docs/user_docs/config-walkthrough/overview.md, docs/user_docs/config-walkthrough/secret.md, docs/user_docs/config-walkthrough/workload.md, docs/user_docs/guides/working-with-k8s/6-differentiated-configuration.md
=> doc: add config walkthrough

docs/operating/manuals/resourceconsist.md
docs/operating/manuals/
```release-note
None
```
=> docs: add docs/operating/manuals/resourceconsist.md

docs/operating/manuals/resourceconsist.md
=> docs: revise docs/operating/manuals/resourceconsist.md title

docs/operating/introduction.md
fix #305 
```release-note
None
```
=> doc(operating): add operating introduction

docs/operating/started/demo-graceful-operation.md
fix #315 
```release-note
None
```
=> doc(operating): add operating tutorial

docs/operating/introduction/introduction.md, docs/operating/started/demo-graceful-operation.md
=> docs: update operating docs

docs/operating/introduction/introduction.md
=> doc(operating): update intro

static/scripts/install.sh
fix: curl permission error in ubuntu, and curl the latest version.
=> fix: curl permission error in ubuntu, and curl the latest version.

docs/operating/introduction/introduction.md
=> Update intro operating

docs/user_docs/concepts/_category_.json, docs/user_docs/concepts/appconfiguration.md, docs/user_docs/concepts/glossary.md, docs/user_docs/concepts/index.md, docs/user_docs/concepts/kcl-lang.md, docs/user_docs/concepts/kusion.md
=> docs: refine concepts

docs/user_docs/intro/kusion-vs-x.md
fix https://github.com/KusionStack/kusion/issues/524
Document update: more detailed info of Kusion compared with other Software
```release-note
None
```
=> feat: update content of Kusion vs Other Software

docusaurus.config.js
Purpose:
* Adjust blog link to blog.kusionstack.io
=> chore: adjust blog link to blog.kusionstack.io

docs/ctrlmesh/started/try.md
controller-mesh sample doc
docs/ctrlmesh/started/try.md
```release-note
None
```
=> doc: update ctrlmesh sample doc

docs/user_docs/reference/cli/backend/_category_.json, docs/user_docs/reference/cli/backend/backend-configuration.md, docs/user_docs/reference/cli/kusion/_category_.json, docs/user_docs/reference/cli/kusion/index.md
fix https://github.com/KusionStack/kusion/issues/580
This PR adds documentation for backend configuration. 
```release-note
None
```
=> feat: add docs for backend configuration

docs/user_docs/getting-started/install.md
=> fix: brew upgrade

docs/operating/manuals/resourceconsist.md
=> Docs: refact docs/operating/manuals/resourceconsist.md

static/operating/index.html, static/resourceconsist/index.html
=> feat: refine go get for operating and resourceconsist

docs/community/intro/intro.md
Remove redundant documents of community.
=> docs: remove redundant documents

docs/user_docs/reference/model/project-stack-config-items.md
fix https://github.com/KusionStack/kusion/issues/572
docs/user_docs/reference/model/project-stack-config-items.md
This PR updates the document for project and stack config items. 
```release-note
None
```
=> feat: update doc for project and stack config items

docs/user_docs/getting-started/install.md
This PR fixes a little problem in the document for kusion cli installation. 
```release-note
None
```
=> fix: update install doc

docs/community/intro/intro.md
modify link of kusion contributing
=> docs: modify kusion contributing

static/kube-utils/index.html, static/rollout/index.html
```
❯ curl -sL '127.0.0.1:8080/kube-utils?go-get=1'|grep go-import
<meta name="go-import" content="kusionstack.io/kube-utils git https://github.com/KusionStack/kube-utils">
❯ curl -sL '127.0.0.1:8080/rollout?go-get=1'|grep go-import
<meta name="go-import" content="kusionstack.io/rollout git https://github.com/KusionStack/rollout">
```
```release-note
None
```
=> add kube-utils and rollout static files

docs/ctrlmesh/started/install.md, docs/ctrlmesh/started/try.md, docs/operating/started/install.md
=> replace helm repo url

static/CNAME
=> fix: remove custom domain for kusionstack.io

docs/operating/started/install.md
=> Update operating installation docs

docs/operating/concepts/podopslifecycle.md
=> doc(operating): correct image ref in markdown for PodOpsLifecycle doc

docs/operating/concepts/podopslifecycle.md
=> doc(operating): correct format for PodOpsLifecycle doc

docs/operating/manuals/poddecoration.md
doc
Added introduction documentation for Operating `PodDecoration`.
```release-note
None
```
=> doc: add Operating PodDecoration-Beta doc

docs/ctrlmesh/started/install.md, docs/ctrlmesh/started/try.md
doc
update controller-mesh sample version (some demo bug fixed)
```release-note
None
```
=> doc: update ctrlmesh doc

docs/user_docs/intro/overview.md, docusaurus.config.js, versioned_docs/version-v0.9/user_docs/intro/overview.md
Fix default page when switch version (community => overview)
Reference:
* https://raw.githubusercontent.com/openkruise/openkruise.io/master/docs/introduction.md
=> fix: default page when switch version (community => overview)

docs/user_docs/guides/cloud-resources/expose-service.md
=> doc: update Expose Application Service Deployed on CSP Kubernetes

docs/user_docs/config-walkthrough/operational_rules.md, docs/user_docs/guides/working-with-k8s/6-set-up-operational-rules.md
=> docs: refresh opsRule docs

docs/user_docs/reference/model/naming-conventions.md
=> docs: delete improper content in naming-conventions

docs/user_docs/config-walkthrough/networking.md, versioned_docs/version-v0.9/user_docs/config-walkthrough/networking.md
=> docs: update networking configuration-walkthrough

docs/operating/manuals/resourceconsist.md
docs/operating/manuals/resourceconsist.md
```release-note
None
```
=> fix: modify incorrect path in docs/operating/manuals/resourceconsist.md

docs/user_docs/concepts/project/definition.md, docs/user_docs/concepts/stack/definition.md, docs/user_docs/config-walkthrough/overview.md, docs/user_docs/guides/working-with-k8s/1-deploy-application.md
=> fix: side-bar positions

docs/user_docs/config-walkthrough/overview.md
=> docs: update configuration overview

docs/kusion/5-user-guides/2-working-with-k8s/1-deploy-application.md, docs/kusion/5-user-guides/2-working-with-k8s/2-container.md, docs/kusion/5-user-guides/2-working-with-k8s/3-service.md, docs/kusion/5-user-guides/2-working-with-k8s/4-image-upgrade.md, docs/kusion/5-user-guides/2-working-with-k8s/5-resource-spec.md, docs/kusion/5-user-guides/2-working-with-k8s/6-set-up-operational-rules.md
=> doc: updated kubernetes user guide

docs/kusion/6-reference/2-modules/2-workspace-configs/1-workload/_category_.json, docs/kusion/6-reference/2-modules/2-workspace-configs/1-workload/job.md, docs/kusion/6-reference/2-modules/2-workspace-configs/1-workload/service.md, docs/kusion/6-reference/2-modules/2-workspace-configs/_category_.json
=> doc: add workload workspace configuration

docs/kusion/6-reference/2-modules/2-workspace-configs/2-networking/_category_.json, docs/kusion/6-reference/2-modules/2-workspace-configs/2-networking/port.md
=> doc: add networking workspace configuration

docs/kusion/5-user-guides/2-working-with-k8s/1-deploy-application.md, docs/kusion/5-user-guides/2-working-with-k8s/2-container.md, docs/kusion/5-user-guides/2-working-with-k8s/3-service.md, docs/kusion/5-user-guides/2-working-with-k8s/4-image-upgrade.md, docs/kusion/5-user-guides/2-working-with-k8s/5-resource-spec.md, docs/kusion/5-user-guides/2-working-with-k8s/6-set-up-operational-rules.md, docs/kusion/5-user-guides/2-working-with-k8s/7-job.md
=> doc: add user guide for job

docusaurus.config.js
Support view measurement by google analytics.
References:
* https://github.com/kubevela/kubevela.github.io/blob/main/docusaurus.config.js#L272
* https://docusaurus.io/docs/3.0.1/api/plugins/@docusaurus/plugin-google-gtag
=> feat: support view measurement by google analytics

docs/kusion/4-configuration-walkthrough/4-workload.md
=> doc: update workload configuration-walkthrough

docs/kusion/2-getting-started/1-install-kusion.md, static/scripts/install.sh
=> doc: update install sh and doc

docs/kusion/5-user-guides/2-working-with-k8s/2-container.md, docs/kusion/5-user-guides/2-working-with-k8s/3-service.md, docs/kusion/5-user-guides/2-working-with-k8s/7-job.md
=> doc: update user guides for workload to include ref to workspace config

docs/kusion/1-what-is-kusion/1-overview.md, docs/kusion/3-concepts/4-workspace.md, docs/kusion/3-concepts/8-how-kusion-works.md
=> docs: add how kusion works in the cocept

docs/kusion/6-reference/2-modules/1-catalog-models/trait/opsrule.md, docs/kusion/6-reference/2-modules/2-workspace-configs/trait/opsrule.md
=> docs: add opsrule references

src/components/DocsRating.js
Migrate the `window.ga` to `window.gtag`, `window.ga` is the old version of Google Analytics.
References:
* https://github.com/facebook/docusaurus/issues/7221
* https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs?hl=zh-cn
* https://developers.google.com/analytics/devguides/collection/gtagjs/events?hl=zh-cn#send_events
=> refactor: migrate ga to gtag

docs/kusion/5-user-guides/5-secrets-management/1-using-cloud-secrets.md, docs/kusion/5-user-guides/5-secrets-management/_category_.json
=> doc: add using cloud secrets management user guide

docs/ctrlmesh/started/try.md, versioned_docs/version-v0.10/ctrlmesh/started/try.md
=> Doc: update controllermesh doc

docs/community/intro/intro.md
=> docs: update the community doc

docusaurus.config.js, i18n/en/code.json, src/pages/index.js
fix https://github.com/KusionStack/kusion/issues/750
/src/pages/index.js
/i18n/en/code.json
/docusaurus.config.js
This PR adjusts the content of the home page of the KusionStack official website
```release-note
None
```
=> refactor: adjust home page

docs/kusion/5-user-guides/1-cloud-resources/2-expose-service.md, docs/kusion/5-user-guides/2-working-with-k8s/7-job.md, versioned_docs/version-v0.10/kusion/5-user-guides/1-cloud-resources/2-expose-service.md, versioned_docs/version-v0.10/kusion/5-user-guides/2-working-with-k8s/7-job.md
=> chore: fix some dead links

src/pages/index.js
=> fix: wrong link of "getting started" in home page

docs/kusion/3-concepts/8-configuration.md
=> fix: variable ref format bug

docs/operating/manuals/collaset.md
=> doc(collaset): introduce CollaSet Replace update policy

docs/operating/concepts/podopslifecycle.md
…workload support
```release-note
None
```
=> doc(PodOpsLifecycle): introduce new PodOpsLifecycle feature: general workload support

docs/kusion/2-getting-started/1-install-kusion.md
=> doc: add windows installation

docs/kusion/2-getting-started/2-deliver-quickstart.md, docs/kusion/5-user-guides/1-cloud-resources/1-database.md, docs/kusion/5-user-guides/1-cloud-resources/2-expose-service.md, docs/kusion/5-user-guides/2-working-with-k8s/1-deploy-application.md
/docs/kusion
This PR fixes some typo in the documents. 
```release-note
None
```
=> fix: some typo

versioned_docs/version-v0.11/kusion/3-concepts/9-how-kusion-works.md, versioned_docs/version-v0.11/kusion/4-configuration-walkthrough/6-database.md, versioned_docs/version-v0.11/kusion/5-user-guides/1-cloud-resources/1-database.md
versioned_docs/version-0.11/kusion
This PR fixes some documents of Kusion v0.11.0. 
```release-note
None
```
=> fix: some documents

docs/kusion/2-getting-started/2-deliver-quickstart.md, docs/kusion/5-user-guides/1-cloud-resources/1-database.md
docs/kusion/2-getting-started/2-deliver-quickstart.md
docs_versioned_docs/version-v0.11/2-getting-started/2-deliver-quickstart.md
```release-note
None
```
=> feat: update kusion quickstart doc and database user guide

docs/kusion/3-concepts/1-project/2-configuration.md, docs/kusion/3-concepts/2-stack/2-configuration.md, docs_versioned_docs/version-v0.11/3-concepts/1-project/2-configuration.md, docs_versioned_docs/version-v0.11/3-concepts/2-stack/2-configuration.md
=> docs: update project&stack file reference

docs/kusion/1-what-is-kusion/2-kusion-vs-x.md, docs_versioned_docs/version-v0.11/1-what-is-kusion/2-kusion-vs-x.md
=> docs: update kusion vs other software

docs/kusion/3-concepts/3-kusion-module/1-overview.md, docs/kusion/3-concepts/3-kusion-module/2-develop-guide.md, docs_versioned_docs/version-v0.11/3-concepts/3-kusion-module/1-overview.md, docs_versioned_docs/version-v0.11/3-concepts/3-kusion-module/2-develop-guide.md
=> docs: update the module guide

docs/karpor/1-getting-started/1-overview.mdx, karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx
=> fix: wrong link of karpor contribute

docs/karpor/4-developer-guide/1-contribution-guide/1-non-code-contribute.md, docs/karpor/4-developer-guide/1-contribution-guide/2-code-contribute.md, docs/karpor/4-developer-guide/2-conventions/3-test-conventions.md, karpor_versioned_docs/version-v0.4/4-developer-guide/1-contribution-guide/1-non-code-contribute.md, karpor_versioned_docs/version-v0.4/4-developer-guide/1-contribution-guide/2-code-contribute.md, karpor_versioned_docs/version-v0.4/4-developer-guide/2-conventions/3-test-conventions.md
=> fix: dead link of karpor document

karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx
=> docs: refine content of karpor vs others

docs/karpor/1-getting-started/1-overview.mdx, karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx
Add karpor vs. kubernetes dashboard part in overview.
```release-note
None
```
=> docs: add karpor vs. kubernetes dashboard part in overview

README.md, docusaurus.config.js
=> chore: turn on the switch of edit page, fix typo

i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/2-installation.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/3-quick-start.md
=> docs: translate install and quick start to zh

docs/karpor/4-developer-guide/1-contribution-guide/2-code-contribute.md, docs/karpor/4-developer-guide/1-contribution-guide/3-roles.md, docs/karpor/4-developer-guide/1-contribution-guide/index.md, docs/karpor/4-developer-guide/2-conventions/4-commit-conventions.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/4-developer-guide/1-contribution-guide/2-code-contribute.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/4-developer-guide/1-contribution-guide/3-roles.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/4-developer-guide/1-contribution-guide/index.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/4-developer-guide/2-conventions/4-commit-conventions.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/4-developer-guide/1-contribution-guide/2-code-contribute.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/4-developer-guide/1-contribution-guide/3-roles.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/4-developer-guide/1-contribution-guide/index.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/4-developer-guide/2-conventions/4-commit-conventions.md, karpor_versioned_docs/version-v0.4/4-developer-guide/1-contribution-guide/2-code-contribute.md, karpor_versioned_docs/version-v0.4/4-developer-guide/1-contribution-guide/3-roles.md, karpor_versioned_docs/version-v0.4/4-developer-guide/1-contribution-guide/index.md, karpor_versioned_docs/version-v0.4/4-developer-guide/2-conventions/4-commit-conventions.md
Optimize contributing guide of karpor.
References:
- https://github.com/KusionStack/community/blob/main/CONTRIBUTING.md#contribute-a-pull-request
- https://github.com/trpc-group/trpc-go/blob/main/CONTRIBUTING.zh_CN.md
```release-note
None
```
=> docs: refine contributor guide of karpor

docs/kusion/3-concepts/7-backend.md
=> doc: update doc backend

docs/kusion/3-concepts/8-configuration.md
=> doc: update doc configuration

i18n/en/docusaurus-plugin-content-docs-docs/current.json, i18n/zh/docusaurus-plugin-content-docs-docs/current.json
i18n/en/docusaurus-plugin-content-docs-docs/current.json
i18n/zh/docusaurus-plugin-content-docs-docs/current.json
This PR corrects the next version of Kusion CLI. 
```release-note
None
```
=> fix: next kusion version

docs/kusion/1-what-is-kusion/1-overview.md, docs_versioned_docs/version-v0.12/1-what-is-kusion/1-overview.md
=> feat: update Kusion overview

docs/karpor/1-getting-started/1-overview.mdx, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/1-overview.mdx, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/1-getting-started/1-overview.mdx, karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx, src/components/KarporButton/style.module.css
=> refactor: optimze mobile experience for karpor

docs/karpor/1-getting-started/1-overview.mdx
=> fix: chaotic style when refresh

docs/kusion/3-concepts/3-kusion-module/2-develop-guide.md, docs/kusion/3-concepts/3-kusion-module/3-app-dev-guide.md, docs_versioned_docs/version-v0.12/3-concepts/3-kusion-module/2-develop-guide.md, docs_versioned_docs/version-v0.12/3-concepts/3-kusion-module/3-app-dev-guide.md
=> docs: update the module user guide

i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/1-overview.mdx, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/1-getting-started/1-overview.mdx
=> docs: add karpor overview zh translate

docs/karpor/1-getting-started/1-overview.mdx, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/1-overview.mdx, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/1-getting-started/1-overview.mdx, karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx
=> fix: karpor zh typo

docusaurus.config.js, package-lock.json, package.json
=> fix: incomplete search of website

docs/kusion/2-getting-started/2-deliver-quickstart.md, docs_versioned_docs/version-v0.12/2-getting-started/2-deliver-quickstart.md
docs_versioned_docs/version-v0.12/2-getting-started/2-deliver-quickstart.md
docs/kusion/2-getting-started/2-deliver-quickstart.md
This PR fixes the sample codes of quickstart demo. 
```release-note
None
```
=> fix: quickstart sample codes

docs/kusion/3-concepts/9-how-kusion-works.md, docs/kusion/4-configuration-walkthrough/3-base-override.md, docs/kusion/4-configuration-walkthrough/6-database.md, docs/kusion/4-configuration-walkthrough/8-monitoring.md, docs/kusion/4-configuration-walkthrough/9-operational-rules.md, docs/kusion/5-user-guides/1-cloud-resources/2-expose-service.md, docs/kusion/5-user-guides/2-working-with-k8s/7-job.md, docs/kusion/6-reference/2-modules/1-developer-schemas/app-configuration.md, docs/kusion/6-reference/2-modules/1-developer-schemas/opsrule/opsrule.md, docs/kusion/6-reference/2-modules/1-developer-schemas/workload/service.md, docs/kusion/6-reference/2-modules/index.md, docs_versioned_docs/version-v0.12/3-concepts/9-how-kusion-works.md, docs_versioned_docs/version-v0.12/4-configuration-walkthrough/3-base-override.md, docs_versioned_docs/version-v0.12/4-configuration-walkthrough/6-database.md, docs_versioned_docs/version-v0.12/4-configuration-walkthrough/8-monitoring.md, docs_versioned_docs/version-v0.12/4-configuration-walkthrough/9-operational-rules.md, docs_versioned_docs/version-v0.12/5-user-guides/1-cloud-resources/2-expose-service.md, docs_versioned_docs/version-v0.12/5-user-guides/2-working-with-k8s/7-job.md, docs_versioned_docs/version-v0.12/6-reference/2-modules/1-developer-schemas/app-configuration.md, docs_versioned_docs/version-v0.12/6-reference/2-modules/1-developer-schemas/opsrule/opsrule.md, docs_versioned_docs/version-v0.12/6-reference/2-modules/1-developer-schemas/workload/service.md, docs_versioned_docs/version-v0.12/6-reference/2-modules/index.md
docs/kusion
docs_versioned_docs/version-v0.12.0
This PR fixes some deprecated sample codes and workspace configs. 
```release-note
None
```
=> fix: deprecated sample codes and workspace configs

docs/kusion/3-concepts/3-module/3-app-dev-guide.md
docs/kusion/3-concepts/3-module/3-app-dev-guide.md
```release-note
None
```
=> fix: update kusion doc to correct developer role

docs/karpor/1-getting-started/1-overview.mdx, karpor_versioned_docs/version-v0.4/1-getting-started/1-overview.mdx, src/components/GithubStars.module.css, src/components/KarporButton/style.module.css
=> feat: improve compatibility with different browsers

docs/kusion/6-reference/3-roadmap.md, docs_versioned_docs/version-v0.12/6-reference/3-roadmap.md
=> docs: update the roadmap

docs/kusion/6-reference/3-roadmap.md, docs_versioned_docs/version-v0.12/6-reference/3-roadmap.md
=> update the roadmap link

docs/karpor/1-getting-started/2-installation.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/2-installation.md
=> docs: add advanced installation for karpor

docs/karpor/1-getting-started/2-installation.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/2-installation.md
Purpose:
- fix wrong anchor in install document
- update chinese install document
- add registryProxy usage
```release-note
None
```
=> docs: refine karpor install

docusaurus.config.js, package-lock.json, src/pages/index.js
There was a lot of spacing, spelling mistake, I have improved the Home Page text to make it more professional plus appealing to developer and companies.
This is likely to increase their interaction with website and more potential of using our product and services.
Before:
After the Changes were made:
This was main highlight as other small changes that use improved sentences of the words being used 
```release-note
This Release changes the HomePage of website and improves the language, indentation and tone of website, making it more appealing to developers and businesses.
```
=> Home Page edit for docs website

docs/kusion/3-concepts/3-module/2-develop-guide.md, docs/kusion/3-concepts/5-appconfiguration.md, docs_versioned_docs/version-v0.12/3-concepts/3-module/2-develop-guide.md, docs_versioned_docs/version-v0.12/3-concepts/5-appconfiguration.md
=> docs: add docs about workload modularization

i18n/zh/docusaurus-plugin-content-docs-karpor/current/4-developer-guide/2-conventions/3-test-conventions.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/4-developer-guide/2-conventions/3-test-conventions.md
=> docs: Convert negative examples to positive in docs_zh

docs/karpor/1-getting-started/2-installation.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/2-installation.md
=> docs: update karpor chart job doc

docs/kusion/3-concepts/1-project/2-configuration.md, docs/kusion/3-concepts/2-stack/2-configuration.md, docs_versioned_docs/version-v0.12/3-concepts/1-project/2-configuration.md, docs_versioned_docs/version-v0.12/3-concepts/2-stack/2-configuration.md
fix https://github.com/KusionStack/kusion/issues/1208
docs/kusion/3-concepts/1-project/2-configuration.md
docs/kusion/3-concepts/2-stack/2-configuration.md
```release-note
None
```
=> docs: add customized namespace examples for kusion project and stack

static/kueperator/index.html
=> Add kuperator index

docs/karpor/3-user-guide/1-multi-cluster-management.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-multi-cluster-management.md
=> docs: add guide of how to add eks in Karpor

docs/karpor/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-how-to-create-token.md
=> docs: adjust description and style in create token

docs/karpor/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-how-to-create-token.md
=> doc: improve karpor token-creating doc

docs/kusion/5-user-guides/2-working-with-k8s/10-customize-health-policy.md
=> docs: add customized health policy user guide

i18n/en/docusaurus-plugin-content-docs-docs/version-v0.12.json, i18n/en/docusaurus-plugin-content-docs-docs/version-v0.13.json
i18n/en/docusaurus-plugin-content-docs
i18n/en/docusaurus-theme-classic
This PR updates the `i18n/en` files for Kusion. 
```release-note
None
```
=> chore: update i18n for kusion

docs/karpor/1-getting-started/3-quick-start.md, docs/karpor/3-user-guide/1-how-to-create-token.md, docs/karpor/3-user-guide/2-multi-cluster-management.md, docs/karpor/5-references/1-cli-commands/1-karpor.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/3-quick-start.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/2-multi-cluster-management.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.4/3-user-guide/1-multi-cluster-management.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.5/1-getting-started/3-quick-start.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.5/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.5/3-user-guide/2-multi-cluster-management.md, karpor_versioned_docs/version-v0.4/3-user-guide/1-multi-cluster-management.md, karpor_versioned_docs/version-v0.5/3-user-guide/1-how-to-create-token.md, karpor_versioned_docs/version-v0.5/3-user-guide/2-multi-cluster-management.md
Fix corrent link 👇
```release-note
None
```
=> fix: correct link in create token

static/kusion-api-go/index.html
- static/kusion-api-go/index.html
This PR adds the go import source of `kusion-api-go`. 
```release-note
None
```
=> feat: add kusion-api-go import source

docs/karpor/1-getting-started/2-installation.md, docs/karpor/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/2-installation.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/version-v0.5/3-user-guide/1-how-to-create-token.md, karpor_versioned_docs/version-v0.5/3-user-guide/1-how-to-create-token.md
=> docs(karpor): improve sed command documentation for cross-platform usage

docs/karpor/1-getting-started/2-installation.md, docs/karpor/1-getting-started/3-quick-start.md, docs/karpor/3-user-guide/1-how-to-create-token.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/1-getting-started/3-quick-start.md, i18n/zh/docusaurus-plugin-content-docs-karpor/current/3-user-guide/1-how-to-create-token.md
=> docs: update guide of enableRbac in production environment

docs/kusion/2-getting-started/3-getting-started-with-kusion-server/0-installation.md
docs/kusion/2-getting-started/0-installation.md
Add kusion server helm chart installation instructions
```release-note
None
```
=> docs: add kusion server installation doc

karpor_versioned_docs/version-v0.6/1-getting-started/2-installation.md
=> docs(installation): Add parameter description for ai.backend
